version: '3.8'

services:
  web:
    build: ./tmp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - ./tmp/main:/usr/src/app/main
      - ./tmp:/usr/src/app
    # networks:
    #   test_network:
    #     ipv4_address: 172.16.238.10
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=bbc_dev

    # networks:
    #   test_network:
    #     ipv4_address: 172.16.238.11
    
  acc_bot:
    build: ./tmp
    command: python manage.py acc_bot
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev
    
    # networks:
    #   test_network:
    #     ipv4_address: 172.16.238.12
    
  naeb_bot:
    build: ./tmp
    command: python manage.py naeb_bot
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev

# networks:
#   test_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.0/24