version: '3.8'

services:
  web:
    build:
      context: ./bbc
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn bbc.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./bbc/bot_constructor:/usr/src/app/bot_constructor
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  bot:
    build: ./bbc
    command: python manage.py bot
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
