services:
  web:
    build: ./tmp
    # command: gunicorn tmp.wsgi:application --bind 0.0.0.0:8000
    command: uvicorn tmp.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - ./tmp/main:/usr/src/app/main
      - ./tmp:/usr/src/app
    # networks:
    #   test_network:
    #     ipv4_address: 172.16.238.10

  ngrok:
    image: ngrok/ngrok
    depends_on:
      - web
    env_file:
      - ./.env.dev 
    command: http web:8000 --url chigger-robust-unicorn.ngrok-free.app
    ports:
      - "4040:4040"


  telegram-webhook-updater:
    build: ./webhook_updater
    env_file:
      - ./.env.dev
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=bbc_dev

    # networks:
    #   test_network:
    #     ipv4_address: 172.16.238.11


# networks:
#   test_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.0/24