version: '3.8'

services:
  web:
    build: .
    restart: always
    command: gunicorn bbc.wsgi:application --bind 0.0.0.0:80
    ports:
      - 8000:80
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=bbc_db

volumes:
  postgres_data: