# Generated by Django 4.1.1 on 2023-07-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_operation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='Без названия', max_length=12, verbose_name='Название таблицы'),
        ),
    ]
