# Generated by Django 4.1.1 on 2023-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.CharField(default='Без описания', max_length=255, verbose_name='Описание платежа'),
        ),
    ]
