# Generated by Django 4.1.1 on 2023-08-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_operation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_categories',
            field=models.BooleanField(default=False, verbose_name='Возможность создавать новые категории'),
        ),
    ]
