# Generated by Django 4.1.1 on 2023-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_can_create_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Доход', 'Доход'), ('Расход', 'Расход')], default='Не определен', max_length=255, verbose_name='Тип категории'),
        ),
    ]
