# Generated by Django 4.1.1 on 2023-08-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отвественный'),
        ),
    ]
