# Generated by Django 4.1.1 on 2023-08-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_operation_category_alter_operation_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_create_categories',
        ),
    ]
