# Generated by Django 4.1.1 on 2023-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_can_create_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название таблицы'),
        ),
    ]
