# Generated by Django 4.1.1 on 2023-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание платежа'),
        ),
    ]
