# Generated by Django 4.1.1 on 2023-11-22 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_operation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления'),
        ),
    ]
