# Generated by Django 4.1.1 on 2023-11-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_operation_creator_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='table',
            field=models.ForeignKey(default='Не определена', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table', verbose_name='Таблица по категории'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(default='Не определен', null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(default='Без категории', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.CharField(default='Без описания', max_length=255, null=True, verbose_name='Описание платежа'),
        ),
    ]
