# Generated by Django 4.1.1 on 2024-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(default=-1, null=True, verbose_name='ID пользователя'),
        ),
    ]
