# Generated by Django 4.1.1 on 2024-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(default=1, null=True, verbose_name='ID пользователя'),
        ),
    ]
