# Generated by Django 4.1.1 on 2023-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='income',
            field=models.BigIntegerField(default=0, verbose_name='Income on apply'),
        ),
        migrations.AlterField(
            model_name='admintransaction',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Отменен', 'Отменен'), ('Проведен', 'Проведен'), ('Создан', 'Создан')], default='Создан', max_length=30, verbose_name='Payment status'),
        ),
    ]
