# Generated by Django 3.1 on 2022-09-29 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(default='none', max_length=50, verbose_name='Function name')),
                ('function_desc', models.TextField(default='none', verbose_name='Function description')),
                ('function_sub', models.CharField(choices=[('default', 'Default'), ('expanded', 'Expanded'), ('pro', 'Pro')], default='default', max_length=12, verbose_name='Type of subscription')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Functions',
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='channel',
            field=models.CharField(max_length=255, null=True, verbose_name='Project channel link'),
        ),
        migrations.AddField(
            model_name='bot',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='Project website link'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(default='Loly', max_length=100, verbose_name='TGBot name'),
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(default=0, verbose_name="Telegram user's id")),
                ('username', models.CharField(default='Ánonymous', max_length=50, verbose_name="Telegram user's username")),
                ('is_admin', models.BooleanField(default=False, verbose_name='Bot admin status')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name="Telegram user's balance")),
                ('experience', models.PositiveIntegerField(default=0, verbose_name="Telegram user's experience")),
                ('rank', models.CharField(default='Vegetable', max_length=30, verbose_name="Telegram user's rank")),
                ('ton_wallet', models.CharField(default=False, max_length=255, verbose_name="Telegram user's TON wallet address")),
                ('whitelisted', models.BooleanField(default=False, verbose_name="Telegram user's whitelist status")),
                ('messages_amount', models.PositiveIntegerField(default=0, verbose_name="Telegram user's messages amount")),
                ('ref_token', models.CharField(default='No token', max_length=255, verbose_name="Telegram user's referral token")),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.bot', verbose_name="Telegram user's bot")),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(default='The best NFT in the world', max_length=50, verbose_name='NFT name')),
                ('nft_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.tguser', verbose_name='NFT creator')),
                ('nft_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NFT owner')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTS',
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='functions',
            field=models.ManyToManyField(to='bot_constructor.Function', verbose_name='Functions included to bot'),
        ),
        migrations.CreateModel(
            name='ReferralLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to='bot_constructor.tguser', verbose_name='Referred user')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_user', to='bot_constructor.tguser', verbose_name='Referrer user')),
            ],
            options={
                'verbose_name': 'Referral link',
                'verbose_name_plural': 'Referral links',
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
