# Generated by Django 3.1 on 2022-09-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='channel',
            field=models.CharField(max_length=255, null=True, verbose_name='Project channel link'),
        ),
        migrations.AddField(
            model_name='bot',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='Project website link'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(default='Loly', max_length=100, verbose_name='TGBot name'),
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(default=0, verbose_name="Telegram user's id")),
                ('username', models.CharField(default='Ánonymous', max_length=50, verbose_name="Telegram user's username")),
                ('is_admin', models.BooleanField(default=False, verbose_name='Bot admin status')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name="Telegram user's balance")),
                ('experience', models.PositiveIntegerField(default=0, verbose_name="Telegram user's experience")),
                ('rank', models.CharField(default='Vegetable', max_length=30, verbose_name="Telegram user's rank")),
                ('ton_wallet', models.CharField(default=False, max_length=255, verbose_name="Telegram user's TON wallet address")),
                ('whitelisted', models.BooleanField(default=False, verbose_name="Telegram user's whitelist status")),
                ('messages_amount', models.PositiveIntegerField(default=0, verbose_name="Telegram user's messages amount")),
                ('ref_token', models.CharField(default='No token', max_length=255, verbose_name="Telegram user's referral token")),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.bot', verbose_name="Telegram user's bot")),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
