# Generated by Django 3.1 on 2022-09-29 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0002_auto_20220929_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(default='The best NFT in the world', max_length=50, verbose_name='NFT name')),
                ('nft_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.tguser', verbose_name='NFT owner')),
                ('nft_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NFT owner')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTS',
            },
        ),
        migrations.CreateModel(
            name='ReferralLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to='bot_constructor.tguser', verbose_name='Referred user')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_user', to='bot_constructor.tguser', verbose_name='Referrer user')),
            ],
            options={
                'verbose_name': 'Referral link',
                'verbose_name_plural': 'Referral links',
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
