# Generated by Django 4.1.1 on 2023-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0002_admintransaction_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name="Telegram user's balance"),
        ),
    ]
