# Generated by Django 4.1.1 on 2023-04-18 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0003_tguser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.BigIntegerField(default=0, verbose_name='TGPayment')),
                ('payment_id', models.CharField(default='No ID', max_length=255, verbose_name='TGPaymentID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.bot', verbose_name='Bot, connected to payment')),
                ('payeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.tguser', verbose_name='Person, who pays')),
            ],
        ),
    ]
