# Generated by Django 3.1 on 2022-09-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0003_nft_referrallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(default='none', max_length=50, verbose_name='Function name')),
                ('function_desc', models.TextField(default='none', verbose_name='Function description')),
                ('function_sub', models.CharField(choices=[('default', 'Default'), ('expanded', 'Expanded'), ('pro', 'Pro')], default='default', max_length=12, verbose_name='Type of subscription')),
            ],
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_constructor.tguser', verbose_name='NFT creator'),
        ),
        migrations.AddField(
            model_name='bot',
            name='functions',
            field=models.ManyToManyField(to='bot_constructor.Function', verbose_name='Functions included to bot'),
        ),
    ]
