# Generated by Django 4.1.1 on 2023-04-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_constructor', '0004_tgpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgpayment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='tgpayment',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='tgpayment',
            name='payeer',
        ),
        migrations.AddField(
            model_name='tgpayment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bot owner'),
        ),
        migrations.AddField(
            model_name='tgpayment',
            name='status',
            field=models.CharField(choices=[('Проведен', 'Проведен'), ('Создан', 'Создан')], default='Создан', max_length=30),
        ),
    ]
