# Generated by Django 4.1.1 on 2023-08-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Админ', 'Админ'), ('Манагер', 'Манагер'), ('Воркер', 'Воркер')], default='Низшая форма жизни', max_length=255, verbose_name='Тип операции')),
                ('telegram_chat_id', models.PositiveBigIntegerField(null=True, verbose_name='ID пользователя')),
                ('username', models.CharField(default='Аноним 🗿', max_length=255, verbose_name='Имя пользователя')),
                ('can_create_tasks', models.BooleanField(default=False, verbose_name='Возможность ставить задачи')),
                ('verified_usr', models.BooleanField(default=False, verbose_name='Верификация пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Безымянная 🌚', max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(default='Без описания', verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(null=True, verbose_name='Дедлайн задачи')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for_task', to='fin_plan.user', verbose_name='Ответственный')),
                ('task_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_task', to='fin_plan.user', verbose_name='Создатель задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='💣 Проект', max_length=255, verbose_name='Название проекта')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_project', to='fin_plan.user', verbose_name='Создатель проекта')),
                ('users', models.ManyToManyField(blank=True, to='fin_plan.user', verbose_name='Проекты пользователя')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Инвайт код')),
                ('valid', models.BooleanField(default=False, verbose_name='Валидность инвайт кода')),
                ('invite_type', models.CharField(choices=[('Манагер', 'Манагер'), ('Воркер', 'Воркер')], default='Низшая форма жизни', max_length=255, verbose_name='Тип инвайта')),
                ('activator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activator_of_invite_token', to='fin_plan.user', verbose_name='Активатор инвайта')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_invite_token', to='fin_plan.user', verbose_name='Создатель инвайта')),
            ],
            options={
                'verbose_name': 'Инвайт код',
                'verbose_name_plural': 'Инвайт коды',
            },
        ),
    ]
