# Generated by Django 4.1.1 on 2023-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(choices=[('Манагер', 'Манагер'), ('Воркер', 'Воркер'), ('Низшая форма жизни', 'Низшая форма жизни')], default='Низшая форма жизни', max_length=255, verbose_name='Тип инвайта'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Валидность инвайт кода'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, to='fin_plan.user', verbose_name='Пользователи проекта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Манагер', 'Манагер'), ('Воркер', 'Воркер'), ('Низшая форма жизни', 'Низшая форма жизни')], default='Низшая форма жизни', max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
