# Generated by Django 4.1.1 on 2023-08-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin_plan', '0002_alter_invite_invite_type_alter_invite_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_of_invite_code', to='fin_plan.project', verbose_name='Проект, в который добавить человека'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code_limits',
            field=models.IntegerField(default=0, verbose_name='Количество созданий инвайт кодов'),
        ),
    ]
