# Generated by Django 4.1.1 on 2023-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_plan', '0003_invite_project_user_invite_code_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Является ли юзер админом'),
        ),
    ]
