# Generated by Django 4.1.1 on 2023-09-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin_plan', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_of_task', to='fin_plan.project', verbose_name='Проект, в который добавить задачу'),
        ),
    ]
