# Generated by Django 4.1.1 on 2024-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.PositiveBigIntegerField(default='Не определен', null=True, verbose_name='ID пользователя')),
                ('verified_usr', models.BooleanField(default=False, verbose_name='Верификация пользователя')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Явлется ли юзер админом')),
                ('username', models.CharField(default='Anonim', max_length=255, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
