# Generated by Django 4.1.1 on 2024-05-20 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Баланс пользователя'),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_id', models.CharField(default='#00000', max_length=255, verbose_name='id чека')),
                ('cheque_sum', models.IntegerField(default=0, verbose_name='Сумма чека')),
                ('cheque_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Подтвержден ли чек')),
                ('is_denied', models.BooleanField(default=False, verbose_name='Отклонен ли чек')),
                ('cheque_owner', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец чека')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
