# Generated by Django 4.1.1 on 2024-05-24 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0002_applyuser_balance_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_id', models.CharField(default='#00000', max_length=255, verbose_name='id вывода')),
                ('withdraw_sum', models.IntegerField(default=0, verbose_name='Сумма вывода')),
                ('withdraw_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вывода')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Подтвержден ли вывод')),
                ('withdraw_owner', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец вывода')),
            ],
            options={
                'verbose_name': 'Вывод',
                'verbose_name_plural': 'Выводы',
            },
        ),
    ]
