# Generated by Django 4.1.1 on 2024-05-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0003_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='course',
            field=models.FloatField(default=0.0, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='usdt_sum',
            field=models.FloatField(default=0.0, verbose_name='Сумма в USDT'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес вывода'),
        ),
    ]
