# Generated by Django 4.1.1 on 2024-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0004_withdraw_course_withdraw_usdt_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='comission',
            field=models.IntegerField(default=8, verbose_name='Комиссия пользователя'),
        ),
        migrations.AddField(
            model_name='applyuser',
            name='income',
            field=models.FloatField(default=0, verbose_name='Наша прибыль'),
        ),
    ]
