# Generated by Django 4.1.1 on 2024-05-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0005_applyuser_comission_applyuser_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyuser',
            name='income',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='income',
            field=models.FloatField(default=0, verbose_name='Наша прибыль'),
        ),
    ]
