# Generated by Django 4.1.1 on 2024-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0006_remove_applyuser_income_withdraw_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='info',
            field=models.TextField(null=True, verbose_name='Информация о юзере'),
        ),
    ]
