# Generated by Django 4.1.1 on 2024-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0007_applyuser_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='income',
        ),
        migrations.AddField(
            model_name='cheque',
            name='income',
            field=models.FloatField(default=0, verbose_name='Наша прибыль'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='usdt_sum',
            field=models.FloatField(default=0.0, null=True, verbose_name='Сумма в USDT'),
        ),
    ]
