# Generated by Django 4.1.1 on 2024-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0008_remove_withdraw_income_cheque_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_card_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Реквизиты фиат вывода'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес крипто вывода'),
        ),
    ]
