# Generated by Django 4.1.1 on 2024-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0009_withdraw_withdraw_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='has_active_withdraw',
            field=models.BooleanField(default=False, verbose_name='Есть ли активный вывод у юзера'),
        ),
    ]
