# Generated by Django 4.1.1 on 2024-09-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0010_applyuser_has_active_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_invited', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_invited_new_user', to='applier.applyuser', verbose_name='Кто пригласил юзера')),
                ('whom_invited', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whom_invited_to_project', to='applier.applyuser', verbose_name='Кого пригласили в проект')),
            ],
            options={
                'verbose_name': 'Реферальная связь',
                'verbose_name_plural': 'Реферальные связи',
            },
        ),
    ]
