# Generated by Django 4.1.1 on 2024-09-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0011_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='ref_income',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Реферальный баланс пользователя'),
        ),
    ]
