# Generated by Django 4.1.1 on 2024-09-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0012_ref_ref_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Баланс пользователя'),
        ),
    ]
