# Generated by Django 5.1.2 on 2024-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0013_alter_applyuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс пользователя'),
        ),
    ]
