# Generated by Django 5.1.2 on 2024-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0014_alter_applyuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Баланс пользователя'),
        ),
    ]
