# Generated by Django 5.1.2 on 2024-11-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0015_alter_applyuser_balance'),
        ('partners_bot', '0011_remove_reks_who_use_reks'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='reks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.reks', verbose_name='Активные реквизиты'),
        ),
    ]
