# Generated by Django 5.1.2 on 2024-11-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0016_applyuser_reks'),
        ('partners_bot', '0012_reks_is_emergency_alter_insurancepayment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='reks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.reks', verbose_name='Активные реквизиты'),
        ),
        migrations.AlterField(
            model_name='applyuser',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец чека'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='who_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_invited_new_user', to='applier.applyuser', verbose_name='Кто пригласил юзера'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='whom_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whom_invited_to_project', to='applier.applyuser', verbose_name='Кого пригласили в проект'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец вывода'),
        ),
    ]
