# Generated by Django 5.1.2 on 2024-12-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0017_alter_applyuser_reks_alter_cheque_cheque_owner_and_more'),
        ('applier', '0017_alter_applyuser_reks_and_more'),
    ]

    operations = [
    ]
