# Generated by Django 5.1.2 on 2024-12-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0018_merge_20241204_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='cheque_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец чека'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='who_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_invited_new_user', to='applier.applyuser', verbose_name='Кто пригласил юзера'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='whom_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whom_invited_to_project', to='applier.applyuser', verbose_name='Кого пригласили в проект'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Владелец вывода'),
        ),
    ]
