# Generated by Django 5.1.2 on 2024-12-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0020_autoacceptcheque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoAcceptCheque',
        ),
    ]
