# Generated by Django 5.1.2 on 2025-01-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0021_delete_autoacceptcheque'),
        ('partners_bot', '0019_alter_reks_reks_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='reks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partners_bot.reks', verbose_name='Активные реквизиты'),
        ),
    ]
