# Generated by Django 5.1.2 on 2025-01-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0024_applyuser_username_of_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyuser',
            name='username_of_telegram',
        ),
        migrations.AddField(
            model_name='applyuser',
            name='telegram_username',
            field=models.CharField(default='91ed4d80-14e9-48cd-8d19-32f99b73ebd5', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
