# Generated by Django 5.1.2 on 2025-01-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0025_remove_applyuser_username_of_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyuser',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='bd920f7e-5c11-4ae9-a1a7-79f713cf1721', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
