# Generated by Django 5.1.2 on 2025-01-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0026_remove_applyuser_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='e6807845-c06a-4648-9d32-feb4bc16d277', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
