# Generated by Django 5.1.2 on 2025-01-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0027_alter_applyuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='e1a3fe79-2bc3-4eb3-8764-f06ec64ad64b', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
