# Generated by Django 5.1.2 on 2025-01-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0028_alter_applyuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='98ee6c90-f504-4d4b-9d89-5c910ce9b861', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
