# Generated by Django 5.1.2 on 2025-01-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0029_alter_applyuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='d71323d2-2d15-4cf6-8c2c-be76e28b1511', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
