# Generated by Django 5.1.2 on 2025-01-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0030_alter_applyuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(default='01ab92b9-c51a-46cf-a424-4df5269c2e9f', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
