# Generated by Django 4.1.1 on 2024-01-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfuser',
            old_name='verified_user',
            new_name='verified_usr',
        ),
        migrations.AddField(
            model_name='tfuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Явлется ли юзер админом'),
        ),
    ]
