# Generated by Django 4.1.1 on 2024-01-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf_maker', '0002_rename_verified_user_tfuser_verified_usr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/tf_photos', verbose_name='Фото')),
                ('custom_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Уникальный id фотки')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Является ли фотка превью')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tf_maker.tfuser', verbose_name='Загрузчик фото')),
            ],
        ),
    ]
