# Generated by Django 4.1.1 on 2024-01-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_maker', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='photo_path',
            field=models.CharField(default='Не определено', max_length=255, verbose_name='Фото'),
        ),
    ]
