# Generated by Django 4.1.1 on 2024-01-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf_maker', '0004_remove_image_photo_image_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания TF')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на телеграф')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tf_maker.tfuser', verbose_name='Загрузчик фото')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
