name: Deploy

on:
  push:
    branches: 
      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/bbc"
  
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd /bbc && docker-compose -f docker-compose.prod.yml up -d --build && docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput && docker-compose -f docker-compose.prod.yml exec web python manage.py collectstatic --no-input --clear 
