# Generated by Django 5.1.2 on 2024-11-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.PositiveBigIntegerField(default='Не определен', null=True, verbose_name='ID пользователя')),
                ('verified_usr', models.BooleanField(default=False, verbose_name='Верификация пользователя')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Явлется ли юзер админом')),
                ('username', models.CharField(default='Anonim', max_length=255, verbose_name='Имя пользователя')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс пользователя')),
                ('comission', models.IntegerField(default=8, verbose_name='Комиссия пользователя')),
                ('is_ready_to_get_money', models.BooleanField(default=False, verbose_name='Может ли юзер принимать деньги на свои реквизиты')),
                ('insurance_deposit', models.BigIntegerField(default=0, verbose_name='Сумма остатка страхового депозита для приема платежей')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
