# Generated by Django 5.1.2 on 2024-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='amount_to_accept',
            field=models.BigIntegerField(default=0, verbose_name='Сколько процессор готов принимать денег'),
        ),
    ]
