# Generated by Django 5.1.2 on 2024-11-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0002_processor_amount_to_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
