# Generated by Django 5.1.2 on 2024-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0003_processor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='comission',
            field=models.IntegerField(default=5, verbose_name='Комиссия пользователя'),
        ),
    ]
