# Generated by Django 5.1.2 on 2024-11-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0004_alter_processor_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='has_active_paying_insurance_apply',
            field=models.BooleanField(default=False, verbose_name='Есть ли у юзера заявка на оплату страхового депозита.'),
        ),
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum_rub', models.FloatField(default=0.0, verbose_name='Сумма страховой оплаты в рублях')),
                ('payment_sum_usdt', models.FloatField(default=0.0, verbose_name='Сумма страховой оплаты в USDT')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Принята ли страховая выплата')),
                ('owner', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец оплаты')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
            },
        ),
    ]
