# Generated by Django 5.1.2 on 2024-11-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0015_alter_applyuser_balance'),
        ('partners_bot', '0005_processor_has_active_paying_insurance_apply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default='0000 0000 0000 0000', max_length=50, verbose_name='Номер карты реквизитов')),
                ('sbp_phone_number', models.CharField(default='+79999999999', max_length=15, verbose_name='Номер телефона для принятия по СБП')),
                ('card_owner_name', models.CharField(default='Иванов Иван Иванович', max_length=100, verbose_name='Имя владельца карты')),
                ('bank_name', models.CharField(max_length=10, null=True, verbose_name='Название банка, которому принадлежит карта.')),
                ('owner', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец реквизитов')),
                ('who_use_reks', models.ForeignKey(default='Не определен', null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Клиент, пользующийся реквизитами.')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
