# Generated by Django 5.1.2 on 2024-11-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0006_reks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reks',
            old_name='owner',
            new_name='reks_owner',
        ),
    ]
