# Generated by Django 5.1.2 on 2024-11-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0015_alter_applyuser_balance'),
        ('partners_bot', '0007_rename_owner_reks_reks_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepayment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец оплаты'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='reks',
            name='reks_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец реквизитов'),
        ),
        migrations.AlterField(
            model_name='reks',
            name='who_use_reks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applier.applyuser', verbose_name='Клиент, пользующийся реквизитами.'),
        ),
    ]
