# Generated by Django 5.1.2 on 2024-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0008_alter_insurancepayment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reks',
            name='bank_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название банка, которому принадлежит карта.'),
        ),
        migrations.AlterField(
            model_name='reks',
            name='sbp_phone_number',
            field=models.CharField(default='+79999999999', max_length=50, verbose_name='Номер телефона для принятия по СБП'),
        ),
    ]
