# Generated by Django 5.1.2 on 2024-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0009_alter_reks_bank_name_alter_reks_sbp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reks',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Флаг для проверки не добавляет ли процессор такие же реквизиты.'),
        ),
    ]
