# Generated by Django 5.1.2 on 2024-11-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0010_reks_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reks',
            name='who_use_reks',
        ),
    ]
