# Generated by Django 5.1.2 on 2024-11-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0011_remove_reks_who_use_reks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reks',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Являются ли реквизиты резервными'),
        ),
        migrations.AlterField(
            model_name='insurancepayment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец оплаты'),
        ),
        migrations.AlterField(
            model_name='reks',
            name='reks_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners_bot.processor', verbose_name='Владелец реквизитов'),
        ),
    ]
