# Generated by Django 5.1.2 on 2024-12-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0012_reks_is_emergency_alter_insurancepayment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='is_ready_to_get_money_first',
            field=models.BooleanField(default=False, verbose_name='Первичная идентификация'),
        ),
    ]
