# Generated by Django 5.1.2 on 2024-12-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0014_alter_processor_managers_processor_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAcceptCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш для чека')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма чека')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Принят ли чек')),
                ('reks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners_bot.reks', verbose_name='Реквизиты для юзера')),
            ],
        ),
    ]
