# Generated by Django 5.1.2 on 2024-12-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0015_autoacceptcheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoacceptcheque',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Хэш для чека'),
        ),
    ]
