# Generated by Django 5.1.2 on 2025-01-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0016_alter_autoacceptcheque_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoacceptcheque',
            name='fail_webhook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка отправки непринятия чека'),
        ),
        migrations.AddField(
            model_name='autoacceptcheque',
            name='success_webhook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка отправки принятия чека'),
        ),
    ]
