# Generated by Django 5.1.2 on 2025-01-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0017_autoacceptcheque_fail_webhook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoacceptcheque',
            options={'verbose_name': 'Автопринятый чек', 'verbose_name_plural': 'Автопринятые чеки'},
        ),
        migrations.RenameField(
            model_name='autoacceptcheque',
            old_name='fail_webhook',
            new_name='redirect_url',
        ),
    ]
