# Generated by Django 5.1.2 on 2025-01-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0018_alter_autoacceptcheque_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reks',
            name='reks_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Владелец реквизитов'),
        ),
    ]
