# Generated by Django 5.1.2 on 2025-01-18 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0019_alter_reks_reks_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='processor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='processor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='autoacceptcheque',
            name='is_denied',
            field=models.BooleanField(default=False, verbose_name='Отклонен ли чек'),
        ),
        migrations.AlterField(
            model_name='insurancepayment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners_bot.processor', verbose_name='Владелец оплаты'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='username',
            field=models.CharField(default='Anonim', max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='reks',
            name='reks_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners_bot.processor', verbose_name='Владелец реквизитов'),
        ),
    ]
