# Generated by Django 5.1.2 on 2025-01-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0020_alter_processor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='clients_withdraw',
            field=models.BigIntegerField(default=0, verbose_name='Сумма вывода клиентских денег'),
        ),
    ]
