# Generated by Django 5.1.2 on 2025-01-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0021_processor_clients_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='device_token',
            field=models.CharField(default='d1c35221-813d-4c09-a547-b6dd70706733', max_length=255),
        ),
    ]
