# Generated by Django 5.1.2 on 2025-01-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_bot', '0022_processor_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='device_token',
            field=models.CharField(default='b26ed40e-c045-492e-b95c-f9e663ac5018', max_length=255),
        ),
    ]
